##### This script creates a name storing data frame for the vegetation data
sppnames <-
  data.frame(stringsAsFactors = F,
             "abb" = 
               c("Acri", 
                 "Bfru",
                 "Bhal",
                 "Cpal",
                 "Dspi",
                 "Hspp",
                 "Ifru",
                 "Jroe",
                 "Lcar",
                 "Malb",
                 "Pame",
                 "Salt",
                 "Slin",
                 "Spat",
                 "Srob",
                 "Ssem",
                 "Sspp",
                 "Vlut",
                 "macroalgae",
                 "mussel",
                 "other",
                 "upland",
                 "oyster",
                 "oyster_live",
                 "oyster_culch",
                 "rock",
                 "wrack",
                 "debris",
                 "snails_m2",
                 "liveStem_m2",
                 "HMean", 
                 "BMMean", 
                 "BMtotal"),
             "sppname" =
               c(
                 "Atriplex cristata",
                 "Borrichia frutescens",
                 "Baccharis halimifolia",
                 "Chynaum palustre",
                 "Distichlis spicata",
                 "Hydrocotyle spp.",
                 "Iva frutescens",
                 "Juncus roemerianus",
                 "Limonium carolinianum",
                 "Melilotus alba",
                 "Phytolacca americana",
                 "Spartina alterniflora",
                 "Suaeda linearis",
                 "Spartina patens",
                 "Scirpus robustus",
                 "Solidago sempervirens",
                 "Salicornia spp.",
                 "Vigna luteola",
                 "Macroalgae",
                 "Mussel",
                 "Other",
                 "Upland",
                 "Oyster",
                 "Live Oyster",
                 "Culch",
                 "Rock",
                 "Wrack",
                 "Debris",
                 "Littorina littorea",
                 "Spartina alterniflora",
                 "Spartina alterniflora",
                 "Spartina alterniflora",
                 "Spartina alterniflora"
               ),
             "commonname" = c(
               "Seabeach Orache",
               "Sea Ox-eye",
               "Groundsel Bush",
               "Milkweed Vine",
               "Seashore Saltgrass",
               "Pennywort",
               "High-tide Bush",
               "Black Needlerush",
               "Carolina Sea-Lavender",
               "White Sweet-Clover",
               "American Pokeweed",
               "Smooth Cordgrass",
               "Annual Seablite",
               "Saltmeadow Coordgrass",
               "Saltmarsh Bulrush",
               "Seaside Goldenrod",
               "Pickleweed",
               "Hairy-Pod Cowpea",
               "Macroalgae",
               "Mussel",
               "Other",
               "Upland",
               "Oyster",
               "Live Oyster",
               "Culch",
               "Rock",
               "Wrack",
               "Debris",
               "Common Periwinkle",
               "Smooth Cordgrass",
               "Smooth Cordgrass",
               "Smooth Cordgrass",
               "Smooth Cordgrass"
             )
  )
# not sure why, but have to create this outside of the initial creation
sppnames$axis.label <- 
  c(
    "A. cristata",
    "B. frutescens",
    "B. halimifolia",
    "C. palustre",
    "D. spicata",
    "Hydrocotyle spp.",
    "I. frutescens",
    "J. roemerianus",
    "L. carolinianum",
    "M. alba",
    "P. americana",
    "S. alterniflora",
    "S. linearis",
    "S. patens",
    "S. robustus",
    "S. sempervirens",
    "Salicornia spp.",
    "V. luteola",
    "Macroalgae",
    "Mussel",
    "Other",
    "Upland",
    "Oyster",
    "Live Oyster",
    "Culch",
    "Rock",
    "Wrack",
    "Debris",
    "L. littorea",
    "S. alterniflora",
    "S. alterniflora",
    "S. alterniflora",
    "S. alterniflora"
  )

sppnames$unitname <- 
  c(
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "Density",
    "Density",
    "Height", 
    "Biomass",
    "Biomass"
  )

sppnames$unit <- 
  c(
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "percent cover",
    "Snails"~m^-2,
    "Live Stems"~m^-2,
    "cm", 
    "g", 
    "g"~m^-2
  )
