---
title: "Linear Mixed Effects Model Repeated Measure"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(comment = NA)

```

```{r libraries, include=FALSE, cache=F}
library(tidyverse)
library(reshape2)
library(lubridate)
library(readr)

library(knitr)
library(tidyverse)
library(nlme)
library(lme4)
library(lmerTest)
```

```{r wrangle, include=FALSE, cache=F}
source("R:/CEE/RC shoreline/Data/Vegetation Data/R Analysis files/combined wrangling.R")
# VegData <- read.csv("R:/CEE/RC shoreline/Data/Vegetation Data/R data/masterVegData.csv", stringsAsFactors = F) %>% 
#   mutate(Date = lubridate::ymd(Date),
#          SampTime = factor(SampTime, levels = paste0(c("SU", "FA"), rep(2006:2019, each = 2))),
#          Season = factor(Season, levels = c("Winter", "Sping", "Summer", "Fall")))

PctCoverColNums <-
  c((which(names(VegData) == "Acri")):(which(names(VegData) == "Snails_per_area") - 1))

QuantColNums <- c(which(names(VegData) == "snails_m2"),
                  which(names(VegData) == "liveStem_m2"),
                  which(names(VegData) == "HMean"))

SppColNums <- c(PctCoverColNums, QuantColNums)

# rm(d, KBDI, localPDSI, localSPI, localSPI.NCCD, masterVegData.summary.trt, masterVegData.summary.trt.ftr, masterVegData.summary.trt.ftr.envi)
# rm(surveyDates, VegData, VegData.melt, VegData.summary, VegData.summary.trt, VegData.summary.trt.ftr, VegData0607, VegData0607.melt, VegData0607.summary, VegData0607.summary.trt, VegData0607.summary.trt.ftr)
# rm(comCols, ct, dat, date, i, names, nms, PctCoverColNums, QuantColNums, run, SppColNums, startMSL, var, yr)
spplist <- list()
spplist$pctcover.plotting <- c("Salt", "Spat", "Sspp", "oyster_live", "oyster_culch", "mussel")
#create a vector of categories that we want to plot (avoids creating too many figures for uncommon categories)
spplist$quant.plotting <- c("liveStem_m2", "HMean", "snails_m2")
#reading in environmental data
envidata <- read.csv(
  "R:/CEE/RC shoreline/Data/Meterological Data/survey dates and environmental variables all.csv",
  stringsAsFactors = F) %>% 
  as.tbl() %>% 
  filter(Site %in% c("PKS", "PI", "NCMM")) %>% 
  dplyr::select("Year", "Site", "SampTime", "Precip.GS.mm",
         "Temp.C.GS.mean", "KBDI.I", "MSL.GS",
         "t.GS", "GS.IT.pct0")

VegData.melt.bb <- VegData.melt %>% 
  filter(Transect != "4a", 
         variable %in% spplist$pctcover.plotting,
         !is.na(value),
         Feature %in% c("None", "Behind", "Oyster"), 
         MarshType ==  "Fringing", 
         Season == "Summer", 
         Site %in% c("PKS", "PI", "NCMM"), 
         Plot <= 20) %>%
  as.tbl() %>% 
  mutate(d.Date = decimal_date(Date), 
         id = paste(Treatment, Site, Transect, Plot),
         valueF = fct_collapse(as.factor(value), 
                               "0" = "0",
                               "0.1" = "0.05",
                               "0.5" = c("0.55", "1.5"),
                               "1" = c("2.55", "3.5"),
                               "2" = c("7.5", "15", "17.5"),
                               "3"= "37.5",
                               "4" = "62.5", 
                               "5" = c("85", "87.5", "97.5")),
         value = as.numeric(as.character(valueF))) %>% 
  left_join(envidata)

VegData.melt.quant <- VegData.melt %>% 
  filter(Transect != "4a", 
         variable %in% spplist$quant.plotting,
         !is.na(value),
         Feature %in% c("None", "Behind", "Oyster"), 
         MarshType ==  "Fringing", 
         Season == "Summer", 
         Site %in% c("PKS", "PI", "NCMM"), 
         Plot <= 20) %>%
  as.tbl() %>% 
  mutate(d.Date = decimal_date(Date), 
         id = paste(Treatment, Site, Transect, Plot)) %>% 
  left_join(envidata)

```

```{r model and output, echo=FALSE, results='asis'}
for(spp in spplist$pctcover.plotting){
  for(plt in unique(VegData.melt.bb$Plot)){
    modeldf  <- VegData.melt.bb %>% 
      filter(variable == spp, 
             Plot == plt) 
    
      e <- tryCatch({
        suppressWarnings(lmeModel <- lmer(value ~ KBDI.I + Treatment * d.Date + (1 | id), modeldf))
        }, error = function(err) {
          # cat(paste("Plot:", plt, "with", spp, "error on model,", err))
          return(err)
          })
    
    
      if(!inherits(e, 'error')) {
        suppressWarnings(
          lmeModel <- lmer(value ~ KBDI.I + Treatment * d.Date + (1 | id), modeldf)
          )
        suppressWarnings(
          LMM <- anova(lmeModel) %>% 
            as.data.frame() %>%
            magrittr::set_rownames(c()) %>% 
            mutate(variable = paste(sppnames[sppnames$abb==spp, "axis.label"], "%cover"), 
                   Plot = plt,
                   term = c("KBDI", "Trt", "Date", "Trt:Date"),
                   P = as.character(signif(`Pr(>F)`, 3)),
                   signif = ifelse(`Pr(>F)` < 0.001, "***",
                                   ifelse(`Pr(>F)` < 0.01, "**", 
                                          ifelse(`Pr(>F)` < 0.05, "*", 
                                                 ifelse(`Pr(>F)` < 0.1, ".", " "))))) %>%
            dplyr::select(variable, Plot, term, everything(), signif, -`Pr(>F)`) %>%
            dplyr::rename_all(list(~make.names(.)))
        )
          } else{
            LMM <- data.frame(variable = paste(sppnames[sppnames$abb==spp, "axis.label"], "%cover"), 
                              Plot = plt,
                              term = NA,
                              "Sum Sq" = NA, 
                              "Mean Sq" = NA, 
                              "NumDF" = NA,
                              "DenDF" = NA, 
                              "F value" = NA, 
                              "P" = NA,
                              signif = " ") %>%
              dplyr::select(variable, Plot, term, everything()) %>% 
              dplyr::rename_all(list(~make.names(.)))
          }
    
    
    if(exists('LMM.bb')){
      suppressWarnings(LMM.bb <- bind_rows(LMM.bb, LMM))
      }else{
        LMM.bb <- LMM
        }
    LMM.bb <- distinct(LMM.bb)
   
  }
   print(
      kable(LMM.bb,
            digits = 2,
            caption = "Type III Analysis of Variance Table"),
      format = "pandoc"
      )
    cat("  \n")
    cat("*Signif. codes: 0 ‘\\*\\*\\*’ 0.001 ‘\\*\\*’ 0.01 ‘\\*’ 0.05 ‘.’ 0.1 ‘ ’ 1*")
    cat("  \n")
    rm(LMM.bb)
}

for(spp in spplist$quant.plotting){
  for(plt in unique(VegData.melt.quant$Plot)){
    modeldf  <- VegData.melt.quant %>% 
      filter(variable == spp, 
             Plot == plt) 
    
      e <- tryCatch({
        suppressWarnings(lmeModel <- lmer(value ~ KBDI.I + Treatment * d.Date + (1 | id), modeldf))
        }, error = function(err) {
          # cat(paste("Plot:", plt, "with", spp, "error on model,", err))
          return(err)
          })
    
    
      if(!inherits(e, 'error')) {
        suppressWarnings(
          lmeModel <- lmer(value ~ KBDI.I + Treatment * d.Date + (1 | id), modeldf)
          )
        suppressWarnings(
          LMM <- anova(lmeModel) %>% 
            as.data.frame() %>%
            magrittr::set_rownames(c()) %>% 
            mutate(variable = paste(sppnames[sppnames$abb==spp, "axis.label"], 
                                               sppnames[sppnames$abb==spp, "unitname"]), 
                   Plot = plt,
                   term = c("Trt", "Date", "Trt:Date"),
                   P = as.character(signif(`Pr(>F)`, 3)),
                   signif = ifelse(`Pr(>F)` < 0.001, "***",
                                   ifelse(`Pr(>F)` < 0.01, "**", 
                                          ifelse(`Pr(>F)` < 0.05, "*", 
                                                 ifelse(`Pr(>F)` < 0.1, ".", " "))))) %>%
            dplyr::select(variable, Plot, term, everything(), signif, -`Pr(>F)`) %>%
            dplyr::rename_all(list(~make.names(.)))
        )
          } else{
            LMM <- data.frame(variable = paste(sppnames[sppnames$abb==spp, "axis.label"], 
                                               sppnames[sppnames$abb==spp, "unitname"]), 
                              Plot = plt,
                              term = NA,
                              "Sum Sq" = NA, 
                              "Mean Sq" = NA, 
                              "NumDF" = NA,
                              "DenDF" = NA, 
                              "F value" = NA, 
                              "P" = NA,
                              signif = " ") %>%
              dplyr::select(variable, Plot, term, everything()) %>% 
              dplyr::rename_all(list(~make.names(.)))
          }
    
    
    if(exists('LMM.bb')){
      suppressWarnings(LMM.bb <- bind_rows(LMM.bb, LMM))
      }else{
        LMM.bb <- LMM
        }
    LMM.bb <- distinct(LMM.bb)
   
  }
   print(
      kable(LMM.bb,
            digits = 2,
            caption = "Type III Analysis of Variance Table"),
      format = "pandoc"
      )
    cat("  \n")
    cat("*Signif. codes: 0 ‘\\*\\*\\*’ 0.001 ‘\\*\\*’ 0.01 ‘\\*’ 0.05 ‘.’ 0.1 ‘ ’ 1*")
    cat("  \n")
    rm(LMM.bb)
}
```
